FROM node:20.4.0-bookworm-slim as base
WORKDIR /frontend

RUN [ "npm", "install", "-g", "npm@9.8.0" ]

FROM base as front
ENV NODE_ENV=development
COPY package*.json ./


RUN [ "npm", "install" ]

COPY . .