version: '3'
services:
  # 参考: https://qiita.com/ucan-lab/items/b094dbfc12ac1cbee8cb
  mysql-db:
    container_name: musql-db
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=Asia/Tokyo
    ports:
      - "3307:3306"
  rails:
    container_name: rails
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
      - ./backend:/rails
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
      - nextjs
    env_file: .env
    restart: always
    tty: true
    environment:
      - RAILS_ENV=development
    command: bin/dev
  nextjs:
    container_name: "nextjs"
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules

volumes:
  db-store: